<#
  build.ps1 - build SampleNex.nex with z88dk, bumping the build number.

  Modelled on ZX-Next-Unite's sibling project build (ZXNextRemote\build.ps1)
  but cut down to what one demo app needs: find z88dk, bump the counter,
  generate the header, run zcc, report the size.

  THE BUILD NUMBER is the point of this app. build_number.txt holds an
  integer; every build increments it and regenerates src\build_number.h, so
  the .nex you just made always prints a number no earlier build printed.
  Push it to the Next and the number on the TV proves the bytes running are
  the bytes you built - not a stale copy on the SD card.

  Usage:
      .\build.ps1                 # bump, compile -> SampleNex.nex
      .\build.ps1 -NoBump         # rebuild WITHOUT bumping (same number)
      .\build.ps1 -Clean          # remove build artifacts and stop
      .\build.ps1 -Sdcc           # compile with zsdcc instead of sccz80

  Exit code 0 on success, non-zero when the build fails - so the VS Code
  task (and the "Build + Send to Next" chain) fails loudly instead of
  pushing a stale .nex.

  z88dk is found via $env:Z88DK_DIR, else C:\z88dk. It must be a build with
  the +zxn target (any current z88dk nightly).
#>
[CmdletBinding()]
param(
    [switch]$NoBump,
    [switch]$Clean,
    [switch]$Sdcc
)

$ErrorActionPreference = 'Stop'
Set-Location $PSScriptRoot

$AppName   = 'SampleNex'
$CounterFile = Join-Path $PSScriptRoot 'build_number.txt'
$HeaderFile  = Join-Path $PSScriptRoot 'src\build_number.h'
$Sources     = @('src\main.c')

# --- artifacts, in one place so -Clean and the pre-build sweep agree ------
$Artifacts = @("$AppName.nex", "$AppName", "$AppName.map", "$AppName.lis",
               'zcc_opt.def', 'src\*.o', '*.o')

function Remove-Artifacts {
    foreach ($pattern in $Artifacts) {
        Get-ChildItem -Path $pattern -ErrorAction SilentlyContinue |
            Remove-Item -Force -ErrorAction SilentlyContinue
    }
}

if ($Clean) {
    Remove-Artifacts
    Write-Host "Cleaned $AppName build artifacts." -ForegroundColor Green
    exit 0
}

# --- 1. locate z88dk ------------------------------------------------------
$Z88dkDir = $null
if ($env:Z88DK_DIR -and (Test-Path (Join-Path $env:Z88DK_DIR 'bin\zcc.exe'))) {
    $Z88dkDir = $env:Z88DK_DIR
} elseif (Test-Path 'C:\z88dk\bin\zcc.exe') {
    $Z88dkDir = 'C:\z88dk'
}
if (-not $Z88dkDir) {
    Write-Host "FAILED: z88dk not found." -ForegroundColor Red
    Write-Host "  Install it, or set Z88DK_DIR to the folder holding bin\zcc.exe." -ForegroundColor Red
    exit 1
}
$zcc = Join-Path $Z88dkDir 'bin\zcc.exe'

# zcc reads these; setting them here means the task needs no shell profile.
$env:ZCCCFG = Join-Path $Z88dkDir 'lib\config'
if ($env:PATH -notlike "*$Z88dkDir\bin*") {
    $env:PATH = (Join-Path $Z88dkDir 'bin') + [System.IO.Path]::PathSeparator + $env:PATH
}

# --- 2. bump the build number --------------------------------------------
$build = 0
if (Test-Path -LiteralPath $CounterFile) {
    $raw = (Get-Content -LiteralPath $CounterFile -Raw).Trim()
    if (-not [int]::TryParse($raw, [ref]$build)) {
        Write-Host "WARNING: $CounterFile did not hold a number ('$raw') - restarting at 0." -ForegroundColor Yellow
        $build = 0
    }
}
if (-not $NoBump) {
    $build++
    Set-Content -LiteralPath $CounterFile -Value $build -Encoding ASCII
}

# The header is GENERATED (and git-ignored): the counter file is the source
# of truth, so a clone builds from whatever number it carries.
$stamp = (Get-Date).ToString('yyyy-MM-dd HH:mm')
@"
/* GENERATED by build.ps1 - do not edit, do not commit.
   The number lives in build_number.txt; every build increments it. */
#ifndef BUILD_NUMBER_H
#define BUILD_NUMBER_H

#define BUILD_NUMBER $build
#define BUILD_STAMP  "$stamp"

#endif
"@ | Set-Content -LiteralPath $HeaderFile -Encoding ASCII

# --- 3. compile -----------------------------------------------------------
# sccz80 (-clib=new) by default: no zsdcc codegen surprises, and this app is
# far too small to need the optimiser. -Sdcc switches to zsdcc for anyone
# wanting to mirror the bigger project's flags.
if ($Sdcc) {
    $cflags = @('-clib=sdcc_iy', '-SO3', '--max-allocs-per-node200000')
} else {
    $cflags = @('-clib=new', '-O2')
}

# +zxn            : the ZX Spectrum Next target
# -subtype=nex    : emit a .nex loadable by NextZXOS / .nexload
# -create-app     : actually produce the loadable file, not just the binary
# -Cz--clean      : let the nex packer tidy its intermediates
# -m              : write the map file (handy when the demo grows)
$zargs = @('+zxn') + $cflags + @(
    '-subtype=nex', '-Cz--clean', '-create-app', '-m',
    '-o', $AppName) + $Sources

Remove-Artifacts
Write-Host "Building $AppName (build $build) with $(if ($Sdcc) { 'zsdcc' } else { 'sccz80' })..." -ForegroundColor Cyan

& $zcc @zargs
if ($LASTEXITCODE -ne 0) {
    Write-Host "FAILED: zcc exited $LASTEXITCODE." -ForegroundColor Red
    exit $LASTEXITCODE
}

$nex = Join-Path $PSScriptRoot "$AppName.nex"
if (-not (Test-Path -LiteralPath $nex)) {
    Write-Host "FAILED: zcc reported success but produced no $AppName.nex." -ForegroundColor Red
    exit 1
}

$size = (Get-Item -LiteralPath $nex).Length
Write-Host ("BUILT: {0}  ({1:N0} bytes)  ->  prints 'Hello Dev Builders {2}!'" -f `
    "$AppName.nex", $size, $build) -ForegroundColor Green
exit 0
