/* SampleNex - the smallest useful ZX Spectrum Next app for demoing the
 * push-to-hardware loop.
 *
 * It prints one line:
 *
 *     Hello Dev Builders 42!
 *
 * where the number is BUILD_NUMBER, bumped by build.ps1 on every single
 * build. That is the whole point: push it to the Next, read the number on
 * the TV, change nothing, build + push again, and the number proves the
 * bytes that just ran are the ones you built seconds ago - not a stale
 * copy left on the SD card.
 *
 * Then it waits for a key. On a machine running the ZX-Next-Unite autoexec
 * loop, exiting hands the Next back to the NextSync Listener, ready for the
 * next push - so the demo cycle is: build+push -> read the number -> press
 * a key -> build+push again.
 */
#include <stdio.h>

#include "build_number.h"      /* generated by build.ps1, see BUILD_NUMBER */

int main(void)
{
    printf("%c", 12);          /* CLS - the new lib's console clear */
    printf("Hello Dev Builders %d!\n", BUILD_NUMBER);
    printf("\n(built %s)\n", BUILD_STAMP);
    printf("\nPress ENTER to exit...\n");

    /* getchar() on the console driver the crt already links, rather than
     * input.h's in_WaitForKey - that one is a CLASSIC-lib symbol and does
     * not resolve under -clib=new, which is what build.ps1 uses. */
    getchar();
    return 0;
}
