/* SampleNex - the smallest useful ZX Spectrum Next app for demoing the
 * push-to-hardware loop.
 *
 * It prints one line:
 *
 *     Hello Dev Builders 42!
 *
 * where the number is BUILD_NUMBER, bumped by build.ps1 on every single
 * build. That is the whole point: push it to the Next, read the number on
 * the TV, change nothing, build + push again, and the number proves the
 * bytes that just ran are the ones you built seconds ago - not a stale
 * copy left on the SD card.
 *
 * ---------------------------------------------------------------------
 * HOW THIS APP ENDS, and why it matters (fixed after a hardware test)
 * ---------------------------------------------------------------------
 * The first version just did `return 0`, which on this target means the
 * crt's "return to basic" exit (crt_on_exit = 0x30002 in z88dk's zxn
 * crt_config.inc). On a machine sitting in the ZX-Next-Unite autoexec
 * loop that is WRONG: BASIC resumes the loop, the loop finds the pushed
 * file and .nexloads it again, and the app runs over and over - three
 * times on the test machine, output piling down the screen, until
 * something gave and the screen filled with garbage.
 *
 * The loop is built around the ZX Next Remote behaviour of SOFT-RESETTING
 * when it exits: the reset IS the "go to the top of the loop". So this app
 * ends the same way - a soft reset through the Next's reset register - and
 * the machine comes back up into the loop, which re-arms the Listener and
 * waits for the next push. Exactly the cycle the demo is selling.
 *
 * (No CLS on entry either: the old `printf("%c", 12)` is what printed the
 * stray '?' at the start of every line on real hardware - this console
 * driver has no form-feed, it just echoes the unknown character. The reset
 * clears the screen, so nothing is needed here.)
 */
#include <stdio.h>
#include <arch/zxn.h>

#include "build_number.h"      /* generated by build.ps1, see BUILD_NUMBER */

int main(void)
{
    printf("Hello Dev Builders %d!\n", BUILD_NUMBER);
    printf("\n(built %s)\n", BUILD_STAMP);
    printf("\nPress ENTER to reset and wait\n");
    printf("for the next push...\n");

    /* getchar() on the console driver the crt already links. input.h's
     * in_WaitForKey is a CLASSIC-lib symbol and does not resolve under
     * -clib=new, which is what build.ps1 uses. */
    getchar();

    /* Soft-reset: hands the machine back to the autoexec loop, which
     * re-arms the NextSync Listener. Never returns. */
    ZXN_WRITE_REG(REG_RESET, RR_SOFT_RESET);

    /* Not reached - but the compiler wants an exit path, and if a future
     * board ever ignored the reset we would rather sit here quietly than
     * fall back into BASIC and be re-loaded in a loop. */
    for (;;) { }

    return 0;
}
